apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
resources:
  - ../../base/cert-manager/
  - ../../base/cert-manager-webhook-hetzner/
  - secret.yaml
  - resources.yaml
