namespace: forgejo

resources:
  - ../../../shared-resources/k8up-secret/
   - ../../../shared-resources/k8up-prebackup/
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - svc.yaml
  - secrets.yaml
  - backup.yaml
  - httproute.yaml
