apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-router
  namespace: netbird-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-router
  template:
    metadata:
      labels:
        app: netbird-router
    spec:
#      securityContext:
#        sysctls:
#          - name: net.ipv4.ip_forward
#            value: "1"
#          - name: net.ipv4.conf.all.forwarding
#            value: "1"
      containers:
        - name: netbird
          image: netbirdio/netbird:0.61.2
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-setup-key
                  key: key
          volumeMounts:
            - name: netbird-client
              mountPath: /var/lib/netbird
          command:
            - sh
            - -c
            - |
              exec netbird up \
                --management-url=https://netbird.fingol.pro \
                --setup-key="$NB_SETUP_KEY" \
                --hostname="k3int-router" \
                --allow-server-ssh=false \
                --log-level=info \
                --foreground-mode
      volumes:
        - name: netbird-client
          persistentVolumeClaim:
            claimName: netbird-client-pvc
