apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-router
  namespace: netbird-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-router
  template:
    metadata:
      labels:
        app: netbird-router
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: netbird
          image: netbirdio/netbird:0.61.2
          args:
            - "--management-url=https://netbird.fingol.pro"
            - "--setup-key=$(NB_SETUP_KEY)"
            - "--hostname=k3s-int"
            - "--log-level=info"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-setup-key
                  key: key
          volumeMounts:
            - name: netbird-client
              mountPath: /var/lib/netbird
      volumes:
        - name: netbird-client
          persistentVolumeClaim:
            claimName: netbird-client-pvc
