apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilarr
  labels:
    app.kubernetes.io/name: profilarr
    app.kubernetes.io/instance: profilarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: profilarr
      app.kubernetes.io/instance: profilarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profilarr
        app.kubernetes.io/instance: profilarr
    spec:
      containers:
        - name: profilarr
          image: santiagosayshey/profilarr:v1.1.3
          env:
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 6868
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /
              port: 6868
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 6868
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 6868
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: profilarr-config-pvc
