apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ext.cluster.local.server: |
    # Forward queries for external cluster to its CoreDNS
    ext.cluster.local:53 {
        errors
        cache 30
        forward . 10.45.0.10
    }
