apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:8qhX3y0Gzqexqw7jeMkoRBbcp+f0T+In0uJ9A3yK2juVtk6hgz8Gg3B8wp0TxT5oxw3kwrzWL59lfSA42V+B79M+DJ+Vpe5mSNbHjNvZV/ZH67wbQIkzxNxIj+yHS2kOmnHlzaxa3yB+zRubA2g1gw81VLb2uEY+MHENaeJqFXAdrubRkT40jih9dZHLrLoFyi69s2pBRVoOgEa3gz2CpEKABfdIKchISJR7E/QI+lasnW57O8rocrNYF3ckyOe+AQeK62eisfe3LdDvtGa2l5s2VYBVKdM6tHDljuDiDd8JHXF0viMgSTNtWrxzjwiVbp+b557aAIYGPdVCw0Jy/J6nTrd3+2gTpnHeiGSAYKsaM0Afz0IZl41n5M8070n1BfVGVr31yb/QuzELK5zHlSs0f6Fu9RN20V8eouNlE4leRqf9Pl0WYk8BLLAfiK59eF8SSIvz6fs5MMsqMBJgJrntW+1VpoMi1x5ewpTqk1mEJ6Fs9sL8kpXRVfK6xPAz8hNJjJASNtOSvNle6PHzxDSzfAvftccSn9+SnbP8yUl4km3qAZSnH/gAWjDwb4N/q5+dppxDoavHTNxGMDARatiCvEHXHYmXZBRBAmol8wHOO4UbEoPMgdD1jQedMwJj81RYKFTXpFd3p7RfwFev3iQRr75bktZYUj4QZa3LmwhbRt8FDNqIKd/j7VvP1pH1VoSVdEcYKTxlkZEyPmFFaYZZihti34uEsf69mx32pwRMaEqgTxvMa0TJC+CVkM2NjR4PL2YKR1mDoBdwuktkmiKxzBUEWc/bG8fxDpSIoiYkFDfUBz6BAvZIwb3GEcjmm3zrfOhusQXJwx3D4IlOAtwuaKv6WyRF5dIQmFvadVA3+/pnbMwD1lFA+8X2rBMzqcJnhwQLiu3sYDb5P3XbFrKOLoqbFqVF2HVy8AiufmPLjiUuQwjBy43Mc2aGdPeC2lbYmp8Q9wngpZwowtcYDVgliyPINQ==,iv:CzyQNj0BdvD9xe7RLlfIvpM++cXLjTkg8KYlNbLB4j0=,tag:2jspsh7vXA+MMcv3iXmCWg==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1F3NEZHS0I1V1lBQndN
            Tk9IWmJxc1NoeXhLSVpqa0c3TFJETzRiSkRJCjNXUnFWRnNwUGZQbW81ZlB3U25K
            YXVkS256M284cHlSbm1sdmVaK3Y5TjQKLS0tIFVvcUNPU2ZxSUUydjlXSi9DS1R6
            RWdTNWpqUXpMcmhwT2dldnRtb01EV0kKGo4MOGcV0pEi82t00uVjG/7oT4/GZeZs
            n2lJMuebQqTvM/jqMrtilFhBZbj4ld4eHs4fefXBbekiewyJ0Vai0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:02:52Z"
    mac: ENC[AES256_GCM,data:T+AJL83ZsIoiHYb+px8LiS5o7VUz8ZfFxWQG4Crz4wbZIs2evg+87KGnM3glQQIdGFSjlTsuudNIuw0tQDAm7+w/FqRbRSEKQOp0AreDvVU7Y+gASed+wQLyOmhZ3Yv9PtsyrRct1Kb71kNq7Z0L2KnLGLowRXhxzbVGP7LHX2g=,iv:j6jyUyPaOiKn+7qEZKLTZ3/iqprSIZ3UdGNCw2JVFvc=,tag:OfzfZrL7iJucJY1vI3HUjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
