apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:ELb1ftbGrdR5XoTbjXWXaTkXDX2MWgIbapvPULW7c321H5P75Eg0VwXagxxGIt75yhP3afqNItUlQdXOhvtS43v+Qe/iuPOs9l6515XEaIjWAylwf3fqTETVEzIwpFRZ6hZ0XyafG6/4O9pl8Jsr03NUDNxNwhwFzoyFhqzTwpEKtnWEQAgAEkJLD6hV3QLOLTEqt+bC/JCKYTdv6hvra4RPrGBd/oV7ANprSKCBCrT0gTgJ/+36FgUv1iBTmAs6fpm19iuaqjhWzdUX5Z6I9chngl2MxfN1gwOJBlI7t0phuekczFOGq90TjbPKkCWKIof/F4k30bldaYxOenIafDe9xMOrw39TljbRAPsa71NstGO93dWtA+tXaT698+XI9YJ+/VynQMHQyW1aiZq2fVf6NV3adpg5vCED1axd2rug3vuGhOu7jCmoNHAfZsJFNS9XoSA/idRXHjasTqPcA0YlyUTLEEBivx3RcWTMRjhNwoHvs6lldkBTsoyJGRbPbCHMvtbrJIEljPaF6/tI0cUbzgo2uwfi/qBIQHf241pyUqQ5EBH4Xld9N2z2Qvydju8QsJ7S3ZXMNe1iCaQwYXupu5T18XSIjqInBVfxO9Wwp1rxWadfUJn284QIpDhV06jGMuqn21Yi8EOCizHZ5SfkbnKuakLWrQpFTsHlBtF8vg37xgopE5uSamuizyIzh0J7pAaR88WaNnI3++Ps8lo+ULzsC3YrLyqP9+2w6Es7/4DjL4pEHm/7sGlQAT1x94lETQLxiMQusMVUgjLt1archrcDYPnV6FHP8nr9+0wyZ26b0ilI4VvKqU53DhCjwsCdcTmd9HbFJBfeBkxRMLOQrg0Vd73gTZa2nrkaVvibqHGgsH26KVVqn8jP3wUtzUCpWub3pyyekWlOCBdWYWJPob2wpNsGzgjnRAyjaNLh0VsIE9GZSSqdmWRCVNJ9uBCvltinK5XrlE41tj0zZAKh/5YSkUnSkFb1YN/vsNal8NhkR2BRNl08Mva1U3wFUPyAQ2uoS+4TR6gUdQMkPLeNnJT11rPF8J2Fkr2vlhNW0IgcaiY=,iv:SUxU+0rOmJs4KXN1aTNlvOptb7jhdtOCB65vceyAkOk=,tag:pzoGWXQq3Inj8TXt6kh8PA==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1F3NEZHS0I1V1lBQndN
            Tk9IWmJxc1NoeXhLSVpqa0c3TFJETzRiSkRJCjNXUnFWRnNwUGZQbW81ZlB3U25K
            YXVkS256M284cHlSbm1sdmVaK3Y5TjQKLS0tIFVvcUNPU2ZxSUUydjlXSi9DS1R6
            RWdTNWpqUXpMcmhwT2dldnRtb01EV0kKGo4MOGcV0pEi82t00uVjG/7oT4/GZeZs
            n2lJMuebQqTvM/jqMrtilFhBZbj4ld4eHs4fefXBbekiewyJ0Vai0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:38:40Z"
    mac: ENC[AES256_GCM,data:ZIvICAdmj8A+YtY0kSbqx+98xUFaDOkBI5qE70Gs2TF9CNHa6vi0yMWj5LqDaLGS2kYHE6uqkYF4BlpuCY8pOFcT4YaCtUg3vCEaWxYL/4iUwADATBUMkNBEJ2HW8PR8BdNqkzahbYvnTOpJM1GXLPtgxrTINcEtXOG9g9e/0I8=,iv:4jXmrgkUsIzCcpfrEMsSyuwB2Mp8BBSwKyU+LFAktoo=,tag:wPLOYhD8y0VJedRd/tPoTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
