apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:aq2penhOdw5sS9XPsWsoOoo4oNei+PbvfVMepsPDf5PTXgWm8FmfByYwz3ftLcF/hDasG95CuuTk9yvRPC4q0bn7vX5W8It6blWDY/qiZvc655rTdNkczSfO2McEJ/V/1JpAoWu8Z6estqD02gMEYBcmGclQZXpnW0dsO//OD6/rIo9oDlpFex5pFT1BmU2upHe7ly8ekMPOL6zlz/JMeLz/P4br+O7J5gboYjgjkR4Ak1qHAfr7d81qkPWzQ/1d3f3dhIY4RxhM642G3GDTACCjugdLP2pEHmUOI9/aZmMW/SEAkwcOzmxuLlbZFBck8z/4i96mfxcWQX4GznQeTBii4JaBk7z/cXNm592LdKDH92WGrwiwG3kvkk7kKpce6k2xqJIaztjzKEAaoAC9CBALb0rB3pi5HMtensZwR68H7CI2R5cnujP1lzJxprXuO3lpjsqiZFFXFg44GRK6WbOaVhjtuFsKkdVFy7mp7/R+UIDUrhGxg5NC5Ai6nQyjtL9FlK0vRDM7VS0INjcCZUI/qnu3U/9k4RbKj9Xyf5cN06yVmtoIwZdzRxZV/nRIiGSNZCJCx02yin+0R3NpmXB+ES9ufjU40sZiOy94zbgtPBO9MzhqGjcAf1+fVdUc+r7FSpf7xeBRsq7YhwgHJP4AgAeK4pkw8RIlT8SDdpqRFtSopnvux7Cj2M2vU2omfstst51IO7kylc28pXC611uc0cAP4/qWDrLhOIs5RFuk+2j/oF5Yo/DlhDgrvjMS7O7/0+CNuSKvMqWSJsLWu8o4jUw9a4Rqw0QCEyZYYVB9NkmVbWqTluz7BVjjsPxryLoE3ODJ/OyuDP924M8ZbJHn1jKwYwWraq1Hc/1IeGYCVWG69WGLrKSQeEzLHX2eZ7LTOh6+Llv9QKqNJwfT,iv:n52bHTEzZR3hc/rEH84I7wKIjHAxQrx/FE1yLGA86h0=,tag:n8Xij/C65LAFMuF4mZiCYw==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1F3NEZHS0I1V1lBQndN
            Tk9IWmJxc1NoeXhLSVpqa0c3TFJETzRiSkRJCjNXUnFWRnNwUGZQbW81ZlB3U25K
            YXVkS256M284cHlSbm1sdmVaK3Y5TjQKLS0tIFVvcUNPU2ZxSUUydjlXSi9DS1R6
            RWdTNWpqUXpMcmhwT2dldnRtb01EV0kKGo4MOGcV0pEi82t00uVjG/7oT4/GZeZs
            n2lJMuebQqTvM/jqMrtilFhBZbj4ld4eHs4fefXBbekiewyJ0Vai0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:11:08Z"
    mac: ENC[AES256_GCM,data:b9+AnAZGFmBHoNHn5TkJZE5MgyhdYR35/HdjJZoB9Kc1apqWjqd1S0wvIo5Pt35hhqxnv4DXlx6KQW5T4JyPee7g2s71YYGGsj/3t5HgvkgAy2OLzMq/tJ+7rGPyGAF6ZnG/6iE6Vlz4ZsvNewYfwtiNzaD1qUdcUvz2EOThRX0=,iv:cwgsxcIPHvWVsG+MhwbnlPLjqeywKkfrJHmZrsucxkE=,tag:HMfwNTTqlc5ks6dxeFN5vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
