namespace: jellyfin

resources:
  - ../../../shared-resources/restic-secret/
  - manifest.yaml
  - storage.yaml
  - backup.yaml
  - httproute.yaml

patches:
  - target:
      kind: Secret
      name: restic-config
    patch: |
      - op: replace
        path: /stringData/RESTIC_REPOSITORY
        value: rest:http://truenas.lan:8888/jellyfin
