apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  vpn.fingol.pro.server: |
    vpn.fingol.pro:53 {
        rewrite stop {
            name exact vpn.fingol.pro k3s-int.nb.fingol.pro
            answer name k3s-int.nb.fingol.pro vpn.fingol.pro
        }
        forward . /etc/resolv.conf
    }
