clusterSecretsPermissions:
  # Required for NBSetupKey validation
  # Required for Ingress functionality to create and validate secrets for routing peers
  allowAllSecrets: true

webhook:
  # Optional, unused if webhook.enableCertManager is set to true
  tls: {}

  # Use cert-manager to provision webhook certificates (recommended)
  enableCertManager: true

operator:
  replicaCount: 1

  serviceAccount:
    create: true
    automount: true

# I don't use this
ingress:
  enabled: false
  namespacedNetworks: false
  router:
    enabled: false
    namespaces: {}
  policies: {}

netbirdAPI:
  keyFromSecret: 
    name: api-secret
    key: key
