managementURL: "https://replaceme.nonexistent"

cluster:
  name: replacename
  dns: replacedns

ingress:
  enabled: true
  allowAutomaticPolicyCreation: true

  router:
    enabled: true
    replicas: 1

  kubernetesAPI:
    enabled: true

netbirdAPI:
  keyFromSecret: 
    name: api-secret
    key: key
