apiVersion: v1
kind: ConfigMap
metadata:
  name: netbird-coturn-initial-config
data:
  turnserver.conf: |-
    realm: netbird.fingol.pro
    listening-ip: 0.0.0.0
    listening-port: 3478
    tls-listening-port: 5349
    min-port: 49152
    max-port: 65535
    log-file: stdout
    pidfile: "/var/tmp/turnserver.pid"
    pkey: "/tls/tls.key"
    cert: "/tls/tls.crt"
    userdb: "/var/db/turndb"
