namespace: koito

resources:
  - ../../../shared-resources/k8up-secret/
  - ../../../shared-resources/k8up-prebackup/
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - svc.yaml
  - httproute.yaml
  - backup.yaml
