apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-authelia
  namespace: traefik-ext
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: stub-website-route
      namespace: stub-website
  to:
    - group: traefik.io
      kind: Middleware
