apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-auth
  namespace: traefik-ext
spec:
  forwardAuth:
    address: "http://authelia.authelia.svc.cluster.local:9091/api/verify"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
