apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-lapi-secrets
    labels:
        k8s-app: crowdsec
        type: lapi
        version: v1
type: Opaque
stringData:
    registrationToken: ENC[AES256_GCM,data:IdwwzgJvft3FSDYlDmfPamWjCj7loFuKgjFagkM1FfuwV6wuL9WqeVwChyqG12tqvpOqc9PTYMZ7hy1trwCGwQ==,iv:sefy6l1TAGx6eFWG6zMhKvE9SFdBnHA/Uhb2SsLGWsU=,tag:SXe2pkcH1Ylca1SoCbLSSQ==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R2ZsSysvaVphbkRISW9a
            L2xXTTlYOVYzMUZNZFBmL2R6Um44MC9Ea1RvClYrVVFKajJhYUZSTVJabnRDYUY2
            Rk03cHg3Rm50Qk9Hc3ZCSWFHRFVmQ2cKLS0tIEhpZ3JGZzg4blVVTFFzc0dVemFq
            NnRweno5V2tLODZTSmRjSDdIU0plTm8Kx5BFQRkI5jKU6Ol05cSNAVkdgT0TdSjX
            cryHecOH01FZ3/OKiA9Ovng+Ug64oTozZNlsFYeU+2NReuA5LF/iMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T18:24:53Z"
    mac: ENC[AES256_GCM,data:C9HH9OHrKJvQ0siyjziMEsZLQOaUofv/64iJfk91lDzZhZCoc7ReI9bCkCNZjliL4uXJmFfGwZApzUp2sPrzG4gD+Xnm3tj6xW/ZtcMSSUOiBHgOzEkGBG+XZbaWsD+fvrrv6Fs+8fpDEignPmF4loMUV6EpM0NZh04KVCYlt4k=,iv:rLbpdbL8ybE3JiwqDXRSr8Ak3JUG4pKszv77T2TcUeM=,tag:UGWy7LVR7gFWhpq0ucqj1w==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
