apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik-ext
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:76d90ZJDuFQIz/mn1tGytjLf7GlgceyA5qSJkP/vuLKttGipLZ87l2+wW1+4,iv:+URM1AFlkP5etb+56Gi86KsMCXc4O71Q8xyFQIlEdRo=,tag:xkhmTbYag8QUphQDlXI6Fg==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYWEwR3I5eU1yUmI3NWZa
            SHh5Vk93OWhQdzh3MFF4NExPZXpMamhTaGdrCmpHcms1akVlT0lUUUpOS0pRTkha
            VkgvV3d1dTllTFJFMk04R21IaGF2ZmMKLS0tIFlRWTNxNkhXNHV3aTc3MmdvT1cv
            V0NwbkhHOVNwejVGZS9IQnZqQXRkaE0KitC6MmkQ1oA0uSVd09pqI83LQwuup4pL
            KyzRU9V7ab/dEKoqeqffz++A0u6nbvwhAyFu2oj0bQT/O5toMVph9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T23:12:53Z"
    mac: ENC[AES256_GCM,data:stBKoiOP4FxqncJO6KlJJ9wUse6yUO4yKr5YAf3ZfSdW4pACWkwAsvbO4GTLe8qz4Zd197PxPI5acGnw0WuuR9CLmYMUnImpAnU2A9eS3v/0exZY8LdoG9UxpLxhxAeSg+b6cB5AIz+5Pv4m9EgdI03cH/4QznkoPoi5nc8f8l8=,iv:k51Ba78MWwyg4dd+4RylrIN/47F8ZhsirM+tXdFzX+w=,tag:iFg4gmCGGCfbZ72M/8lwWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
