apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik-ext
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:EbvtvFctcmjHzj7tIB+0k6orMngRH+z1NPjj4xlZd+gk69VVsfyeuDYY8Tnd,iv:tTY2Jo0GhsZXSvV6Z6R6NnpbfMAZilgRhd18N95bKfE=,tag:RSxyC1ka2b56VhV2bLnOTg==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1d1NWUjJodktkUlY5VkZH
            a3pkcWp2WUpSekJMYVR6d3VzRmV4dm8vS25zCnMzbTVVZjBXcmZicVpOWmV5NDBR
            MHJnM0hNZnBCQVhoNTZkenYzV2VjbjgKLS0tIHN2RUM4dU43LzR1bXdwVGI5aVcx
            VUZodDdUOWNOZDI4Z3h5WG9EY3RVWDgKUk4GsmR+ppw4grAatPslFDSKnSZOCwB1
            q0zFdJCxxYi7uUhEnFK7+z+avtSdyO+87Muo50M0Irhrfgm2fMwm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T19:33:47Z"
    mac: ENC[AES256_GCM,data:q5bfKQ8wEI9eNxsigfoBYMus8EEmQOb3Bb8PUAOaJETcd6p5fgiJHfzrV1vpuuw63o2pSf469QpwwwmRGkCbLk33qsTHxILeV2eYlV6+6FApbtTQP5Bd90RosAkjw4q43YI9z4ZiboGBfNIOcT1BZSeWFa6pbbSH+yO9x5aBMfg=,iv:N245w0dhwkXQAKxzk69/mOMGaOZi4smgrIHsmHT9C5Y=,tag:IKWl2Kcn6xqSjMG2bUZw/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
