apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik-ext
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:La1gcf09AnnoYOfDRvTees+zpR4ojmFLR7FuC3RMuq6ypDy5j9nXsNFIWTTxOg==,iv:vL14KGxgYhJ1ODzOrUiWvU5q+RDzi6D71gph/1CF/io=,tag:9kKEfp0bU3ujdR04wL6Vgg==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYWEwR3I5eU1yUmI3NWZa
            SHh5Vk93OWhQdzh3MFF4NExPZXpMamhTaGdrCmpHcms1akVlT0lUUUpOS0pRTkha
            VkgvV3d1dTllTFJFMk04R21IaGF2ZmMKLS0tIFlRWTNxNkhXNHV3aTc3MmdvT1cv
            V0NwbkhHOVNwejVGZS9IQnZqQXRkaE0KitC6MmkQ1oA0uSVd09pqI83LQwuup4pL
            KyzRU9V7ab/dEKoqeqffz++A0u6nbvwhAyFu2oj0bQT/O5toMVph9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T22:55:46Z"
    mac: ENC[AES256_GCM,data:SI3/CPVpCxDbThu+uZ8gLqaFPZh2T/Ry1w/kvYlTtKlOZy3XUTprGMAdevFjZKuk2FIYd/il3B33pfieX6eWGg6Q8DRUW2VlNiWa6my/wZsMQtz8YwTk0cB0+n2NeKJm8mEu18AXzDPE4mxQqhLKY1lWSjTS7UCCDefRvT2mjYA=,iv:ZBtfcxIPNr2juhJxZ7dU0ADuL6jzwBcT6n8FJmk4+wg=,tag:Fix6MOY8qAb5BcW0rfO7Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
