apiVersion: v1
kind: ConfigMap
metadata:
  name: slskd-config-template
data:
  slskd.yml: |
    soulseek:
      # a listening port will be replaced dynamically on startup
      listen_port: 88888
      description: O hi!
