apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  labels:
    app.kubernetes.io/name: slskd
    app.kubernetes.io/instance: slskd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: slskd
      app.kubernetes.io/instance: slskd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slskd
        app.kubernetes.io/instance: slskd
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command:
            - sh
            - -c
            - |
              if [ ! -f /app/slskd.yml ]; then
                cp /config-template/slskd.yml /app/slskd.yml
                echo "Created slskd.yml from template"
              else
                echo "slskd.yml already exists"
              fi
          volumeMounts:
            - name: data
              mountPath: /app
            - name: config-template
              mountPath: /config-template

        - name: gluetun
          image: qmcgaw/gluetun:v3.41
          # restartPolicy: Always makes gluetun a native sidecar
          # if you do not add restartPolicy the other init containers will never start
          # it will be an initContainer and not a native sidecar container https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
          restartPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: VPN_SERVICE_PROVIDER
            - name: VPN_TYPE
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: VPN_TYPE
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: WIREGUARD_PRIVATE_KEY
            - name: SERVER_COUNTRIES
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: SERVER_COUNTRIES
            - name: UPDATER_PERIOD
              value: "24h"
            - name: BLOCK_MALICIOUS
              value: "off"
            - name: PORT_FORWARD_ONLY
              value: "on"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: /bin/sh -c 'sed -i -r "s/^([[:space:]]+)#?([[:space:]]*listen_port:).*/\1\2 $(cat /tmp/gluetun/forwarded_port)/" /app/slskd.yml'
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "5030"
            # Killswitch settings
            - name: FIREWALL
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/16,10.43.0.0/16"  # K3s pod and service CIDRs
            - name: DOT
              value: "off"
          ports:
            - containerPort: 5030 # slskd web ui
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /app
          readinessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

      containers:
        - name: slskd
          image: slskd/slskd:latest
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: SLSKD_SLSK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: SLSKD_SLSK_USERNAME
            - name: SLSKD_SLSK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slskd-secret
                  key: SLSKD_SLSK_PASSWORD
            - name: SLSKD_CONFIG
              value: "/app/slskd.yml" # should match a path from VPN_PORT_FORWARDING_UP_COMMAND
            - name: DOTNET_USE_POLLING_FILE_WATCHER # disables auto-reload on config changes to prevent inotify leak (not needed anyway)
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /app
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /shares/music
            - name: books
              mountPath: /shares/books
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /
              port: 5030
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5030
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5030
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: music
          persistentVolumeClaim:
            claimName: music-pvc
        - name: books
          persistentVolumeClaim:
            claimName: books-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: config-template
          configMap:
            name: slskd-config-template
