namespace: readeck

resources:
  - ../../../shared-resources/k8up-secret/
  - ../../../shared-resources/k8up-prebackup/
  - namespace.yaml
  - deployment.yaml
  - storage.yaml
  - svc.yaml
  - httproute.yaml
  - backup.yaml
